# Generated by Django 3.2.9 on 2021-12-09 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20211209_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title', '-created_at']},
        ),
    ]
